# Pre-commit configuration for Libraries.io MCP Server
# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # General checks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
      
      # Security checks
      - id: secrets
        args: ['--multiline', '--secrets-pattern', '(?i)(api_key|secret|password|token)[\\s_-]*[:=][\\s_]*[\'"]?([0-9a-zA-Z\-_]{16,})[\'""]?']
      
      # Python-specific checks
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-python-dateutil]
        args: [--ignore-missing-imports]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, src/, -f, json, -o, bandit-report.json]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=google, --match-dir=(?!tests).*]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: [-d, relaxed]

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [--verbose, --ignore-init-module, --ignore-magic, --ignore-module]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        args: [--rcfile=pyproject.toml, --load-plugins=pylint.extensions.docparams]
        additional_dependencies: [pylint-docparams]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.12.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
      - id: blackdoc

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.4.0
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=72, --wrap-descriptions=72]

  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        args: [--rcfile=pyproject.toml, --load-plugins=pylint.extensions.docparams]
        additional_dependencies: [pylint-docparams]

# Default language version
default_language_version:
  python: python3.8

# Default stages
default_stages: [commit, push]

# Fail fast
fail_fast: true

# Minimum pre-commit version
minimum_pre_commit_version: '2.20.0'

# Files to exclude
exclude: >
  (?x)^(
    \.git/
    | \.tox/
    | \.venv/
    | venv/
    | env/
    | \.eggs/
    | \.mypy_cache/
    | \.pytest_cache/
    | \.coverage
    | \.coverage.*
    | \.cache
    | \.idea/
    | \.vscode/
    | \.DS_Store
    | \.env
    | \.env.*
    | node_modules/
    | dist/
    | build/
    | *.egg-info/
    | __pycache__/
    | *.py[cod]
    | \.so
    | \.pyo
    | \.pyd
    | \.hypothesis/
    | \.coverage
    | \.coverage.*
    | \*.cover
    | .coverage.*
    | .coverage
    | htmlcov/
    | .pytest_cache/
    | .mypy_cache/
    | .tox/
    | .nox/
    | .venv/
    | venv/
    | env/
    | ENV/
    | env.bak/
    | venv.bak/
    | \.env.local
    | \.env.development.local
    | \.env.test.local
    | \.env.production.local
    | \.env.staging.local
    | \.env.production
    | \.env.staging
    | \.env.development
    | \.env.test
    | \.env.example
    | \.env.sample
    | \.env.template
    | \.env.backup
    | \.env.bak
    | \.env.old
    | \.env.swp
    | \.env.swo
    | \.env~
    | \.env.*
    | \.coverage
    | \.coverage.*
    | \*.cover
    | .coverage.*
    | .coverage
    | htmlcov/
    | .pytest_cache/
    | .mypy_cache/
    | .tox/
    | .nox/
    | .venv/
    | venv/
    | env/
    | ENV/
    | env.bak/
    | venv.bak/
    | \.env.local
    | \.env.development.local
    | \.env.test.local
    | \.env.production.local
    | \.env.staging.local
    | \.env.production
    | \.env.staging
    | \.env.development
    | \.env.test
    | \.env.example
    | \.env.sample
    | \.env.template
    | \.env.backup
    | \.env.bak
    | \.env.old
    | \.env.swp
    | \.env.swo
    | \.env~
    | \.env.*
    | \.coverage
    | \.coverage.*
    | \*.cover
    | .coverage.*
    | .coverage
    | htmlcov/
    | .pytest_cache/
    | .mypy_cache/
    | .tox/
    | .nox/
    | .venv/
    | venv/
    | env/
    | ENV/
    | env.bak/
    | venv.bak/
    | \.env.local
    | \.env.development.local
    | \.env.test.local
    | \.env.production.local
    | \.env.staging.local
    | \.env.production
    | \.env.staging
    | \.env.development
    | \.env.test
    | \.env.example
    | \.env.sample
    | \.env.template
    | \.env.backup
    | \.env.bak
    | \.env.old
    | \.env.swp
    | \.env.swo
    | \.env~
    | \.env.*
  )$